-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 15:36:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agencia_bancaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agencia_bancaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agencia_bancaria` DEFAULT CHARACTER SET utf8 ;
USE `Agencia_bancaria` ;

-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cpf` VARCHAR(10) NULL,
  `e-mail` VARCHAR(45) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NOT NULL,
  `num_rua` VARCHAR(4) NOT NULL,
  `complemento` VARCHAR(4) NULL,
  `pix_cpf` VARCHAR(45) NULL,
  `pix_telefone` VARCHAR(45) NULL,
  `pix_cnpj` VARCHAR(45) NULL,
  `pix_email` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `modfied` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`agencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `funcionario_id` INT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `num_rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_conta` ENUM('poupanca', 'corrente', 'investimento') NOT NULL DEFAULT 'corrente',
  `saldo` DOUBLE NULL,
  `cliente_id` INT NOT NULL,
  `agencia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conta_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_conta_agencia1_idx` (`agencia_id` ASC),
  CONSTRAINT `fk_conta_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Agencia_bancaria`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_agencia1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `Agencia_bancaria`.`agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`transacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conta_id` INT NOT NULL,
  `conta_cliente_id` INT NOT NULL,
  `tipo_transacao` ENUM('ted', 'pix', 'doc', 'boleto') NULL,
  `acao_realizada` ENUM('credito', 'debito') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transacoes_Conta1_idx` (`conta_id` ASC, `conta_cliente_id` ASC),
  CONSTRAINT `fk_Transacoes_Conta1`
    FOREIGN KEY (`conta_id`)
    REFERENCES `Agencia_bancaria`.`conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`cargo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agencia_bancaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agencia_bancaria`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(8) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `salario` DECIMAL(6,2) NULL,
  `agencia_id` INT NOT NULL,
  `cargo_id` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `num` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionario_Agencia1_idx` (`agencia_id` ASC),
  INDEX `fk_Funcionario_Cargo1_idx` (`cargo_id` ASC),
  CONSTRAINT `fk_Funcionario_Agencia1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `Agencia_bancaria`.`agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `Agencia_bancaria`.`cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
