-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 10:41:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mercadinhos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadinhos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadinhos` DEFAULT CHARACTER SET utf8 ;
USE `mercadinhos` ;

-- -----------------------------------------------------
-- Table `mercadinhos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinhos`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `perco` DECIMAL(9,4) NULL,
  `estoque` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinhos`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinhos`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `fone` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinhos`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinhos`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `cliente` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes_idx` (`cliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`cliente`)
    REFERENCES `mercadinhos`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinhos`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinhos`.`Itens` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `produto` INT NULL,
  `pedido` INT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Itens_pedidos1_idx` (`pedido` ASC) VISIBLE,
  INDEX `fk_Itens_produtos1_idx` (`produto` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_pedidos1`
    FOREIGN KEY (`pedido`)
    REFERENCES `mercadinhos`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_produtos1`
    FOREIGN KEY (`produto`)
    REFERENCES `mercadinhos`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinhos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinhos`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
