-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 10:29:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mercadinho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mercadinho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mercadinho` DEFAULT CHARACTER SET utf8 ;
USE `mercadinho` ;

-- -----------------------------------------------------
-- Table `mercadinho`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinho`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `perco` DECIMAL(9,4) NULL,
  `estoque` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinho`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `fone` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinho`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinho`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `cliente` INT NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_clientes_idx` (`cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`cliente`)
    REFERENCES `mercadinho`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `mercadinho`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mercadinho`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mercadinho`.`Itens` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `produto` INT NULL,
  `pedido` INT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Itens_pedidos1_idx` (`pedido` ASC) VISIBLE,
  INDEX `fk_Itens_produtos1_idx` (`produto` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_pedidos1`
    FOREIGN KEY (`pedido`)
    REFERENCES `mercadinho`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_produtos1`
    FOREIGN KEY (`produto`)
    REFERENCES `mercadinho`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
